#!/usr/bin/python
# -*- coding: utf-8 -*-

#   This file is part of the xc2424scan project
#   Copyright (C) 2006 Mathieu Bouchard <mbouchar@bioinfo.ulaval.ca>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

from PyQt4.QtCore import QObject, SIGNAL
from PyQt4.QtGui import QApplication


import sys

try:
    from xc2424scan.ui.fscan import FScan
except ImportError:
    print "WARNING: The xc2424scan package could not be loaded"
    print "         Trying to load cmedit from the \"src\" directory"

    sys.path.insert(0, "src")
    
    try:
    	from xc2424scan.ui.fscan import FScan
    	print "The xc2424scan package has been found"
    	print ""
    except ImportError, e:
    	print "ERROR: The xc2424scan package could not be loaded"
    	print "       Please check your installation or add the xc2424scan"
    	print "       package to PYTHONPATH and try again"
    	print "The error was : ", e
    	sys.exit(1)

if __name__ == "__main__":
    app = QApplication(sys.argv)
    win = FScan()
    win.show()

    QObject.connect(app, SIGNAL("lastWindowClosed()"), sys.exit)
    
    app.exec_()
